"""Altered DB structure

Revision ID: b933607d4b72
Revises: 134734dd3b1d
Create Date: 2025-01-25 07:59:07.934535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b933607d4b72'
down_revision: Union[str, None] = '134734dd3b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factory_department')
    op.add_column('departments', sa.Column('factory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'factories', ['factory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'factory_id')
    op.create_table('factory_department',
    sa.Column('factory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='factory_department_department_id_fkey'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], name='factory_department_factory_id_fkey'),
    sa.PrimaryKeyConstraint('factory_id', 'department_id', name='factory_department_pkey')
    )
    # ### end Alembic commands ###
